import type { CategoryInput, JobFixture, ScoreCategory } from "./types";

const reasons: Record<ScoreCategory, string> = {
  roleFit: "The work centers on complex product workflows and end-to-end ownership.",
  seniorityFit: "Scope and influence are consistent with senior-level practice.",
  domainFit: "The product domain overlaps with supplied career context.",
  strategicScope: "The role partners with product leadership on direction and outcomes.",
  handsOnDesign: "The designer remains close to research, interaction, and delivery.",
  portfolioEvidence: "Existing enterprise and systems work should provide relevant evidence.",
  compensationFit: "The stated range appears directionally aligned; confirm exact needs.",
  locationFit: "The working model is compatible with a US-based remote search.",
  companyPreference: "The organization and problem space appear broadly relevant.",
  riskPenalty: "No material concern identified beyond normal diligence.",
};

function evaluation(
  values: [number, number, number, number, number, number, number, number, number, number],
  overrides: Partial<Record<ScoreCategory, string>> = {},
): CategoryInput[] {
  const categories: ScoreCategory[] = [
    "roleFit",
    "seniorityFit",
    "domainFit",
    "strategicScope",
    "handsOnDesign",
    "portfolioEvidence",
    "compensationFit",
    "locationFit",
    "companyPreference",
    "riskPenalty",
  ];
  return categories.map((category, index) => ({
    category,
    rating: values[index],
    reason: overrides[category] ?? reasons[category],
    evidence:
      category === "portfolioEvidence"
        ? "Candidate context: enterprise software, workflow design, systems thinking, and regulated products."
        : undefined,
  }));
}

export const SYNTHETIC_JOBS: JobFixture[] = [
  {
    id: "northstar-staff",
    title: "Staff Product Designer, Platform",
    company: "Northstar Ledger",
    companyInitials: "NL",
    location: "United States",
    remoteStatus: "Remote",
    employmentType: "Full-time",
    compensation: "$185k–$220k + equity",
    posted: "Today",
    source: "Company site",
    sourceUrl: "https://example.com/synthetic/northstar-ledger",
    status: "Strong Match",
    description:
      "Synthetic posting: Lead the design of interconnected risk, permissions, and reconciliation workflows for a growing financial operations platform. Partner with product and engineering leaders while remaining hands-on from discovery through launch.",
    requirements: [
      "10+ years designing complex B2B software",
      "Systems-level interaction and workflow design",
      "Evidence of strategic leadership and hands-on delivery",
      "Experience with regulated or financial products preferred",
    ],
    concerns: ["Broad platform remit may require careful prioritization"],
    companyNotes: "Synthetic company. Verify funding, design maturity, and leadership expectations.",
    evaluationInputs: evaluation([1, 1, 1, 1, 0.95, 1, 0.95, 1, 0.85, 0.12]),
  },
  {
    id: "civicgrid-principal",
    title: "Principal Product Designer",
    company: "CivicGrid",
    companyInitials: "CG",
    location: "Chicago, IL",
    remoteStatus: "Hybrid · 1 day/mo",
    employmentType: "Full-time",
    compensation: "$175k–$205k",
    posted: "Yesterday",
    source: "LinkedIn",
    sourceUrl: "https://example.com/synthetic/civicgrid",
    status: "Strong Match",
    description:
      "Synthetic posting: Shape service-delivery tools used by state and local agencies. Define product strategy, simplify policy-heavy workflows, and improve the design system across a suite of case-management products.",
    requirements: [
      "Deep complex-workflow portfolio",
      "Experience influencing multi-product strategy",
      "Research and service-design fluency",
      "Ability to strengthen a shared design system",
    ],
    concerns: ["Monthly on-site planning in Chicago"],
    companyNotes: "Synthetic company. Government technology is relevant; inspect procurement exposure and pace.",
    evaluationInputs: evaluation([0.97, 1, 0.98, 1, 0.88, 0.95, 0.88, 0.9, 0.9, 0.16]),
  },
  {
    id: "keystone-lead",
    title: "Lead Product Designer, Construction Cloud",
    company: "Keystone Works",
    companyInitials: "KW",
    location: "Austin, TX",
    remoteStatus: "Remote · US",
    employmentType: "Full-time",
    compensation: "$155k–$185k",
    posted: "2 days ago",
    source: "Built In",
    sourceUrl: "https://example.com/synthetic/keystone",
    status: "Possible",
    description:
      "Synthetic posting: Own planning and field-coordination workflows for commercial construction teams. Mentor two designers and partner with a VP of Product on a platform redesign.",
    requirements: ["7+ years in product design", "B2B SaaS workflows", "Mentorship", "Mobile and desktop design"],
    concerns: ["Compensation ceiling may be below target", "Role may include informal people management"],
    companyNotes: "Synthetic company. Relevant domain; clarify leadership model and compensation.",
    evaluationInputs: evaluation([0.9, 0.82, 0.95, 0.78, 0.9, 0.88, 0.55, 1, 0.76, 0.35], {
      riskPenalty: "Compensation and management expectations need clarification.",
    }),
  },
  {
    id: "relay-founding",
    title: "Founding Product Designer",
    company: "Relay HealthOps",
    companyInitials: "RH",
    location: "New York, NY",
    remoteStatus: "Remote · ET hours",
    employmentType: "Full-time",
    compensation: "$170k–$210k + equity",
    posted: "3 days ago",
    source: "Wellfound",
    sourceUrl: "https://example.com/synthetic/relay",
    status: "Possible",
    description:
      "Synthetic posting: Establish the product practice for a clinical operations startup and design a new workflow product from zero to one.",
    requirements: ["Foundational product design", "Healthcare workflows", "Research with clinical teams", "Startup ambiguity"],
    concerns: ["Seed-stage stability", "No existing design team", "High execution breadth"],
    companyNotes: "Synthetic company. Strong problem-space fit; risk profile requires deliberate review.",
    evaluationInputs: evaluation([0.88, 0.84, 0.86, 0.9, 1, 0.84, 0.82, 0.88, 0.68, 0.62], {
      riskPenalty: "Seed-stage stability and solo-design load are meaningful risks.",
    }),
  },
  {
    id: "vector-senior",
    title: "Senior Product Designer, Developer Experience",
    company: "Vector Runtime",
    companyInitials: "VR",
    location: "North America",
    remoteStatus: "Remote",
    employmentType: "Full-time",
    compensation: "$165k–$198k",
    posted: "5 days ago",
    source: "Company site",
    sourceUrl: "https://example.com/synthetic/vector",
    status: "Possible",
    description:
      "Synthetic posting: Improve deployment, observability, and team-administration experiences for a developer platform used by enterprise teams.",
    requirements: ["Developer tools portfolio", "Enterprise administration", "Technical research", "Design system contribution"],
    concerns: ["Developer-tool depth is preferred", "Title may undersell actual experience"],
    companyNotes: "Synthetic company. Relevant enterprise complexity; validate technical-domain expectations.",
    evaluationInputs: evaluation([0.86, 0.72, 0.7, 0.76, 0.94, 0.68, 0.8, 1, 0.8, 0.32], {
      riskPenalty: "Preferred developer-tool depth and level calibration require validation.",
    }),
  },
  {
    id: "shopwave-growth",
    title: "Senior Product Designer, Growth",
    company: "Shopwave Social",
    companyInitials: "SS",
    location: "San Francisco, CA",
    remoteStatus: "Hybrid · 3 days/wk",
    employmentType: "Full-time",
    compensation: "$180k–$215k",
    posted: "4 days ago",
    source: "LinkedIn",
    sourceUrl: "https://example.com/synthetic/shopwave",
    status: "Rejected",
    description:
      "Synthetic posting: Optimize consumer acquisition funnels, social sharing, and rapid experimentation for a mobile commerce app.",
    requirements: ["Consumer growth experimentation", "Mobile social products", "High-volume A/B testing", "On-site collaboration"],
    concerns: ["Consumer growth focus", "Three required office days", "Limited systems or workflow scope"],
    companyNotes: "Synthetic company. Product shape and working model do not align strongly.",
    evaluationInputs: evaluation([0.35, 0.68, 0.28, 0.3, 0.75, 0.32, 0.85, 0.1, 0.32, 0.8], {
      riskPenalty: "Consumer growth focus and mandatory on-site schedule are major mismatches.",
    }),
  },
  {
    id: "adforge-ui",
    title: "UI/Visual Designer",
    company: "AdForge Studio",
    companyInitials: "AS",
    location: "Los Angeles, CA",
    remoteStatus: "On-site",
    employmentType: "Contract",
    compensation: "$70–$85/hr",
    posted: "1 week ago",
    source: "Indeed",
    sourceUrl: "https://example.com/synthetic/adforge",
    status: "Rejected",
    description:
      "Synthetic posting: Produce campaign landing pages, display concepts, and marketing assets for entertainment clients.",
    requirements: ["Agency visual design", "Campaign production", "Adobe Creative Suite", "On-site availability"],
    concerns: ["Marketing-production role", "Contract", "On-site", "No product strategy"],
    companyNotes: "Synthetic company. Work is outside the target product-design scope.",
    evaluationInputs: evaluation([0.12, 0.28, 0.12, 0.08, 0.45, 0.18, 0.42, 0.05, 0.18, 0.95], {
      riskPenalty: "The role is marketing production rather than product design.",
    }),
  },
  {
    id: "pocketplay-junior",
    title: "Product Designer II",
    company: "PocketPlay",
    companyInitials: "PP",
    location: "Seattle, WA",
    remoteStatus: "Hybrid · 2 days/wk",
    employmentType: "Full-time",
    compensation: "$115k–$140k",
    posted: "8 days ago",
    source: "Company site",
    sourceUrl: "https://example.com/synthetic/pocketplay",
    status: "Rejected",
    description:
      "Synthetic posting: Design seasonal engagement features for a casual mobile gaming product under the direction of a senior designer.",
    requirements: ["3–5 years of experience", "Consumer mobile portfolio", "Game economy familiarity", "Hybrid Seattle schedule"],
    concerns: ["Level mismatch", "Compensation below likely range", "Consumer gaming focus", "Required relocation"],
    companyNotes: "Synthetic company. Clear mismatch across level, domain, and work model.",
    evaluationInputs: evaluation([0.22, 0.1, 0.12, 0.08, 0.7, 0.15, 0.18, 0.08, 0.2, 0.95], {
      riskPenalty: "Level, domain, compensation, and location are all materially misaligned.",
    }),
  },
];
